### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by Partyschaum** [Partyschaum/micronaut-kotlin-demo#1]
# Initial Setup

I want a working basic setup using Micronaut, Kotlin and Kotest. I want continuous integration also.

## Todo

- [x] Setup Micronaut via `mn` CLI tool
- [x] Configure [Kotest](https://github.com/kotest/kotest)
- [x] Add the obligatory ["hello world" HTTP endpoint](https://docs.micronaut.io/latest/guide/index.html#creatingServer)
- [ ] Setup [CircleCI](https://circleci.com/)
- [ ] Document project intent and setup in a `README.md` file
